---
name: Build Aunali1s Kernel Package

# yamllint disable-line rule:truthy
on:
  [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
      - name: 'Set up Python 3.9'
        uses: actions/setup-python@v2
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
          sudo apt-get install shellcheck bash
      - name: 'Analysing the code'
        run: |
          yamllint .
          shellcheck ./*.sh

  build-latest-aunali1:
    needs: [lint]
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: find latest release
        id: variables
        run: |
          sudo apt install wget
          wget https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh
          chmod +x ubuntu-mainline-kernel.sh
          VERSION=$(./ubuntu-mainline-kernel.sh -r v5.12 | grep v | rev | cut -d'v' -f 1 | rev | tail -1)
          RELEASE_SUFFIX=t2-aunali1
          REL=$(./next_version.sh ${VERSION}-${RELEASE_SUFFIX})
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=releaseSuffix::${RELEASE_SUFFIX}"
          echo "::set-output name=tag::${VERSION}-${RELEASE_SUFFIX}-${REL}"

      - name: Build script
        id: build
        run: |
          rm -rf /tmp/artifacts
          mkdir /tmp/artifacts
          echo Building ${{ steps.variables.outputs.tag }}
          ./build.sh \
             --kernel=${{ steps.variables.outputs.version }} \
             --kernelBranch="v${{ steps.variables.outputs.version }}" \
             --kernelRepository="git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git" \
             --patchset1Repo="git://github.com/aunali1/linux-mbp-arch.git" \
             --patchset1Branch=master \
             --patchset1Commit=9511d5ed2ae0e851dd6a82843daefb2be7d5e212 \
             --patchset1Filter="grep -vE '000[0-9]'" \
             --releaseSuffix=${{ steps.variables.outputs.version }} \
             --releasePath=/tmp/artifacts
          cd /tmp/artifacts
          ls -l
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          ls -l

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-${{ steps.variables.outputs.tag }}
          path: /tmp/artifacts/*

      - name: Release
        if: |
          github.ref == 'refs/heads/master' ||
          startsWith(github.ref, 'refs/heads/release/')
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Linux official kernel.
            Patchsets:
              https://github.com/aunali1/linux-mbp-arch excluding 0001 to 0009
          files: |
            /tmp/artifacts/Packages.gz
            /tmp/artifacts/sha256
            /tmp/artifacts/*.deb
          tag_name: v${{ steps.variables.outputs.tag }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Kernel
        if: |
          github.ref == 'refs/heads/master' ||
          startsWith(github.ref, 'refs/heads/release/')
        run: |
          PAYLOAD='{"request": {"branch":"master","sha":"9c060e2ebc7564921e28632232131e1dd80ce679"}}'
          curl -sSf -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "Travis-API-Version: 3" \
            -H "Authorization: token ${TRAVIS_TOKEN}" \
            -d "{\"request\": {${PAYLOAD}}}" \
            https://api.travis-ci.com/repo/marcosfad%2Fmbp-ubuntu-kernel/requests
        env:
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}

  build-latest-aunali1-jamlam:
    needs: [lint]
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: find latest release
        id: variables
        run: |
          sudo apt install wget
          wget https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh
          chmod +x ubuntu-mainline-kernel.sh
          VERSION=$(./ubuntu-mainline-kernel.sh -r v5.12 | grep v | rev | cut -d'v' -f 1 | rev | tail -1)
          RELEASE_SUFFIX=t2-aunali1-patched
          REL=$(./next_version.sh ${VERSION}-${RELEASE_SUFFIX})
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=releaseSuffix::${RELEASE_SUFFIX}"
          echo "::set-output name=tag::${VERSION}-${RELEASE_SUFFIX}-${REL}"

      - name: Build script
        id: build
        run: |
          rm -rf /tmp/artifacts
          mkdir /tmp/artifacts
          echo Building ${{ steps.variables.outputs.tag }}
          ./build.sh \
             --kernel=${{ steps.variables.outputs.version }} \
             --kernelBranch="v${{ steps.variables.outputs.version }}" \
             --kernelRepository="git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git" \
             --patchset1Repo="git://github.com/aunali1/linux-mbp-arch.git" \
             --patchset1Branch=master \
             --patchset1Commit=9511d5ed2ae0e851dd6a82843daefb2be7d5e212 \
             --patchset1Filter="grep -vE '000[0-9]'" \
             --patchset2Repo="git://github.com/jamlam/mbp-16.1-linux-wifi.git" \
             --patchset2Branch=main \
             --patchset2Commit=843ecfcaaec0a10707d447ac6d1840db940a9d29 \
             --patchset2Filter="grep -E '8001'" \
             --releaseSuffix=${{ steps.variables.outputs.version }} \
             --releasePath=/tmp/artifacts
          cd /tmp/artifacts
          ls -l
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          ls -l

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-${{ steps.variables.outputs.tag }}
          path: /tmp/artifacts/*

      - name: Release
        if: |
          github.ref == 'refs/heads/master' ||
          startsWith(github.ref, 'refs/heads/release/')
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Linux official kernel.
            Patchsets:
              https://github.com/aunali1/linux-mbp-arch excluding 0001 to 0009
              https://github.com/jamlam/mbp-16.1-linux-wifi only 8001
          files: |
            /tmp/artifacts/Packages.gz
            /tmp/artifacts/sha256
            /tmp/artifacts/*.deb
          tag_name: v${{ steps.variables.outputs.tag }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Kernel
        if: |
          github.ref == 'refs/heads/master' ||
          startsWith(github.ref, 'refs/heads/release/')
        run: |
          PAYLOAD='{"request": {"branch":"master","sha":"9c060e2ebc7564921e28632232131e1dd80ce679"}}'
          curl -sSf -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "Travis-API-Version: 3" \
            -H "Authorization: token ${TRAVIS_TOKEN}" \
            -d "{\"request\": {${PAYLOAD}}}" \
            https://api.travis-ci.com/repo/marcosfad%2Fmbp-ubuntu-kernel/requests
        env:
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
